In [1]:
import numpy as np

In [2]:
np.array([21,4,5,6,7,3,5])

array([21,  4,  5,  6,  7,  3,  5])

In [3]:
np.array([21,4,5,6,7,3,5,10.56,17.33])

array([21.  ,  4.  ,  5.  ,  6.  ,  7.  ,  3.  ,  5.  , 10.56, 17.33])

In [4]:
np.array([[3,1,4],[5,3,6],[7,3,6]])

array([[3, 1, 4],
       [5, 3, 6],
       [7, 3, 6]])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.random()

0.7743451973958579

In [10]:
np.random.random(4)

array([0.79897779, 0.42793929, 0.32808006, 0.54772599])

In [11]:
np.random.random((4,4))

array([[0.77469862, 0.7731223 , 0.10079017, 0.09503956],
       [0.89179337, 0.04099293, 0.37183661, 0.23615456],
       [0.63118171, 0.99601104, 0.30057169, 0.87459394],
       [0.80710619, 0.2686141 , 0.1045154 , 0.25147496]])

In [12]:
np.random.randint(10,20)

15

In [13]:
np.random.randint(10,20,5)

array([18, 15, 18, 13, 11])

In [14]:
np.random.randint(10,20,(4,5))

array([[16, 17, 13, 19, 16],
       [12, 10, 19, 12, 10],
       [14, 11, 11, 19, 15],
       [15, 19, 12, 19, 13]])

In [15]:
x = np.random.randint(10,200,15)

In [16]:
x

array([ 47, 169,  49,  24,  46, 147,  36, 173, 193,  96, 104,  37,  38,
        27, 181])

In [17]:
np.mean(x)

91.13333333333334

In [18]:
np.median(x)

49.0

In [19]:
np.var(x)

3846.7822222222226

In [20]:
np.sum(x)

1367

In [21]:
np.max(x)

193

In [22]:
np.min(x)

24

In [27]:
np.argmax(x)

8

In [24]:
x

array([ 47, 169,  49,  24,  46, 147,  36, 173, 193,  96, 104,  37,  38,
        27, 181])

In [23]:
x[0]

47

In [26]:
x[0:4]

array([ 47, 169,  49,  24])

In [28]:
x = np.random.randint(10,20,(4,6))

In [29]:
x

array([[12, 14, 16, 18, 19, 17],
       [19, 11, 16, 18, 11, 16],
       [13, 11, 12, 13, 11, 17],
       [15, 14, 12, 16, 13, 10]])

In [30]:
x[0]

array([12, 14, 16, 18, 19, 17])

In [31]:
x[0][0]

12

In [32]:
x[0:]

array([[12, 14, 16, 18, 19, 17],
       [19, 11, 16, 18, 11, 16],
       [13, 11, 12, 13, 11, 17],
       [15, 14, 12, 16, 13, 10]])

In [33]:
x[:]

array([[12, 14, 16, 18, 19, 17],
       [19, 11, 16, 18, 11, 16],
       [13, 11, 12, 13, 11, 17],
       [15, 14, 12, 16, 13, 10]])

In [34]:
x[:,0]

array([12, 19, 13, 15])

In [35]:
x[:, 0:1]

array([[12],
       [19],
       [13],
       [15]])

In [36]:
x[:,2:4]

array([[16, 18],
       [16, 18],
       [12, 13],
       [12, 16]])

In [37]:
x[0:3]

array([[12, 14, 16, 18, 19, 17],
       [19, 11, 16, 18, 11, 16],
       [13, 11, 12, 13, 11, 17]])

In [38]:
x[0:, 2:5]

array([[16, 18, 19],
       [16, 18, 11],
       [12, 13, 11],
       [12, 16, 13]])

In [39]:
x[:,[1,3,4]]

array([[14, 18, 19],
       [11, 18, 11],
       [11, 13, 11],
       [14, 16, 13]])

In [40]:
x

array([[12, 14, 16, 18, 19, 17],
       [19, 11, 16, 18, 11, 16],
       [13, 11, 12, 13, 11, 17],
       [15, 14, 12, 16, 13, 10]])

In [41]:
np.mean(x)

14.333333333333334

In [42]:
np.mean(x, axis=0)

array([14.75, 12.5 , 14.  , 16.25, 13.5 , 15.  ])

In [43]:
np.mean(x, axis=1)

array([16.        , 15.16666667, 12.83333333, 13.33333333])

In [44]:
x.shape

(4, 6)

In [45]:
x.reshape(6,4)

array([[12, 14, 16, 18],
       [19, 17, 19, 11],
       [16, 18, 11, 16],
       [13, 11, 12, 13],
       [11, 17, 15, 14],
       [12, 16, 13, 10]])

In [46]:
x.reshape(3,8)

array([[12, 14, 16, 18, 19, 17, 19, 11],
       [16, 18, 11, 16, 13, 11, 12, 13],
       [11, 17, 15, 14, 12, 16, 13, 10]])

In [47]:
x.reshape(2,-1)

array([[12, 14, 16, 18, 19, 17, 19, 11, 16, 18, 11, 16],
       [13, 11, 12, 13, 11, 17, 15, 14, 12, 16, 13, 10]])

In [48]:
x.reshape(-1, 8)

array([[12, 14, 16, 18, 19, 17, 19, 11],
       [16, 18, 11, 16, 13, 11, 12, 13],
       [11, 17, 15, 14, 12, 16, 13, 10]])

In [50]:
x = x.flatten()

In [51]:
x

array([12, 14, 16, 18, 19, 17, 19, 11, 16, 18, 11, 16, 13, 11, 12, 13, 11,
       17, 15, 14, 12, 16, 13, 10])

In [52]:
x = x.reshape(-1, 8)

In [53]:
x

array([[12, 14, 16, 18, 19, 17, 19, 11],
       [16, 18, 11, 16, 13, 11, 12, 13],
       [11, 17, 15, 14, 12, 16, 13, 10]])

In [54]:
# transpose
x.T

array([[12, 16, 11],
       [14, 18, 17],
       [16, 11, 15],
       [18, 16, 14],
       [19, 13, 12],
       [17, 11, 16],
       [19, 12, 13],
       [11, 13, 10]])

In [57]:
# inverse matrix
# np.linalg.inv()

In [58]:
# broadcasting

In [59]:
x = np.zeros((4,5))

In [60]:
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [61]:
x + 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [62]:
x = np.random.randint(10,20,(4,6))

In [63]:
x

array([[16, 19, 12, 14, 18, 11],
       [12, 19, 10, 16, 17, 12],
       [16, 14, 16, 12, 15, 15],
       [19, 12, 12, 13, 18, 19]])

In [64]:
x * 2

array([[32, 38, 24, 28, 36, 22],
       [24, 38, 20, 32, 34, 24],
       [32, 28, 32, 24, 30, 30],
       [38, 24, 24, 26, 36, 38]])