In [1]:
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('headbrain.csv')

In [3]:
X = df['Head Size(cm^3)'].values
y = df['Brain Weight(grams)'].values

In [5]:
X = np.reshape(X, (-1,1))

In [6]:
regression = LinearRegression()
regression.fit(X,y)

LinearRegression()

In [7]:
regression.coef_

array([0.26342934])

In [8]:
regression.intercept_

325.5734210494428

In [9]:
y_pred = regression.predict(X)

In [10]:
y[:10]

array([1530, 1297, 1335, 1282, 1590, 1300, 1400, 1255, 1355, 1375],
      dtype=int64)

In [11]:
y_pred[:10]

array([1514.16660083, 1310.27229206, 1448.04583661, 1320.5460363 ,
       1425.9177721 , 1269.96760312, 1322.65347102, 1263.11844029,
       1277.34362462, 1374.5490509 ])