<a href="https://colab.research.google.com/github/brainmentorspvtltd/DU_PythonDLApril/blob/main/DeepLearningScratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
X = np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
y = np.array([[1],[1],[0]])

In [ ]:
X

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [ ]:
y

array([[1],
       [1],
       [0]])

In [ ]:
X.shape

(3, 4)

In [ ]:
input_neurons = X.shape[1]
hidden_neurons = 3
output_neurons = 1

In [ ]:
input_neurons

4

In [ ]:
wh = np.random.uniform(size=(input_neurons,hidden_neurons))
bh = np.random.uniform(size=(1, hidden_neurons))
wout = np.random.uniform(size=(hidden_neurons, output_neurons))
bout = np.random.uniform(size=(1, output_neurons))

In [ ]:
epochs = 20000
alpha = 0.01

In [ ]:
# for feed forward we need sigmoid
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

# for backpropagation we need derivative of sigmoid
def derivative_sigmoid(x):
  return x * (1 - x)

In [ ]:
#feed forward
z1 = np.dot(X, wh) + bh
hidden_layer = sigmoid(z1)

z2 = np.dot(hidden_layer, wout) + bout
output_layer = sigmoid(z2)

In [ ]:
output_layer

array([[0.78647852],
       [0.79985979],
       [0.79476739]])

In [ ]:
# Back propagation
error_output_layer = y - output_layer
slope_output_layer = derivative_sigmoid(output_layer)
delta_output_layer = error_output_layer * slope_output_layer

In [ ]:
error_hidden_layer = delta_output_layer.dot(wout.T)
slope_hidden_layer = derivative_sigmoid(hidden_layer)
delta_hidden_layer = error_hidden_layer * slope_hidden_layer

In [ ]:
wout += hidden_layer.T.dot(delta_output_layer) * alpha
wh += X.T.dot(delta_hidden_layer) * alpha
bout += np.sum(delta_output_layer) * alpha
bh += np.sum(delta_hidden_layer) * alpha

In [ ]:
for i in range(epochs):
  #feed forward
  z1 = np.dot(X, wh) + bh
  hidden_layer = sigmoid(z1)

  z2 = np.dot(hidden_layer, wout) + bout
  output_layer = sigmoid(z2)

  # Back propagation
  error_output_layer = y - output_layer
  slope_output_layer = derivative_sigmoid(output_layer)
  delta_output_layer = error_output_layer * slope_output_layer

  error_hidden_layer = delta_output_layer.dot(wout.T)
  slope_hidden_layer = derivative_sigmoid(hidden_layer)
  delta_hidden_layer = error_hidden_layer * slope_hidden_layer

  wout += hidden_layer.T.dot(delta_output_layer) * alpha
  wh += X.T.dot(delta_hidden_layer) * alpha
  bout += np.sum(delta_output_layer) * alpha
  bh += np.sum(delta_hidden_layer) * alpha

In [ ]:
output_layer

array([[0.95868604],
       [0.93960412],
       [0.08198208]])

In [ ]:
error_output_layer

array([[ 0.04131396],
       [ 0.06039588],
       [-0.08198208]])