<a href="https://colab.research.google.com/github/brainmentorspvtltd/DU_PythonDLApril/blob/main/NumpyIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#shift+enter = to execute a cell

In [ ]:
np.array([3,4,3,2,5,7,8,5,12,45,67,1])

array([ 3,  4,  3,  2,  5,  7,  8,  5, 12, 45, 67,  1])

In [ ]:
np.array([3,4,3,2,5,7,8,5,12,45,67,1,34.33])

array([ 3.  ,  4.  ,  3.  ,  2.  ,  5.  ,  7.  ,  8.  ,  5.  , 12.  ,
       45.  , 67.  ,  1.  , 34.33])

In [ ]:
np.array([[5,4,4,76],[1,3,4,2],[6,5,7,8]])

array([[ 5,  4,  4, 76],
       [ 1,  3,  4,  2],
       [ 6,  5,  7,  8]])

In [ ]:
x = np.array([[5,4,4,76],[1,3,4,2],[6,5,7,8]])

In [ ]:
x

array([[ 5,  4,  4, 76],
       [ 1,  3,  4,  2],
       [ 6,  5,  7,  8]])

In [ ]:
# convert 2d to 1d
x = x.flatten()

In [ ]:
x

array([ 5,  4,  4, 76,  1,  3,  4,  2,  6,  5,  7,  8])

In [ ]:
len(x)

12

In [ ]:
x.reshape(3,4)

array([[ 5,  4,  4, 76],
       [ 1,  3,  4,  2],
       [ 6,  5,  7,  8]])

In [ ]:
x.reshape(4,3)

array([[ 5,  4,  4],
       [76,  1,  3],
       [ 4,  2,  6],
       [ 5,  7,  8]])

In [ ]:
x.reshape(-1,4)

array([[ 5,  4,  4, 76],
       [ 1,  3,  4,  2],
       [ 6,  5,  7,  8]])

In [ ]:
x[0]

5

In [ ]:
x[5]

3

In [ ]:
# last index
x[-1]

8

In [ ]:
x[0:4]

array([ 5,  4,  4, 76])

In [ ]:
x[4:]

array([1, 3, 4, 2, 6, 5, 7, 8])

In [ ]:
x = x.reshape(4,3)

In [ ]:
x

array([[ 5,  4,  4],
       [76,  1,  3],
       [ 4,  2,  6],
       [ 5,  7,  8]])

In [ ]:
x[0]

array([5, 4, 4])

In [ ]:
x[0][0]

5

In [ ]:
x[:]

array([[ 5,  4,  4],
       [76,  1,  3],
       [ 4,  2,  6],
       [ 5,  7,  8]])

In [ ]:
x[0,2]

4

In [ ]:
x[0,:]

array([5, 4, 4])

In [ ]:
x[:,0]

array([ 5, 76,  4,  5])

In [ ]:
x[:, [0,2]]

array([[ 5,  4],
       [76,  3],
       [ 4,  6],
       [ 5,  8]])

In [ ]:
x[:, 0:2]

array([[ 5,  4],
       [76,  1],
       [ 4,  2],
       [ 5,  7]])

In [ ]:
# transpose
x.T

array([[ 5, 76,  4,  5],
       [ 4,  1,  2,  7],
       [ 4,  3,  6,  8]])

In [ ]:
x[:,1:2]

array([[4],
       [1],
       [2],
       [7]])

In [ ]:
x[:][0]

array([5, 4, 4])

In [ ]:
x.shape

(4, 3)

In [ ]:
x1 = np.array([[3,2,14]])

In [ ]:
np.r_[x,x1]

array([[ 5,  4,  4],
       [76,  1,  3],
       [ 4,  2,  6],
       [ 5,  7,  8],
       [ 3,  2, 14]])

In [ ]:
x2 = np.array([[12],[56],[44],[33]])
np.c_[x,x2]

array([[ 5,  4,  4, 12],
       [76,  1,  3, 56],
       [ 4,  2,  6, 44],
       [ 5,  7,  8, 33]])

In [ ]:
x = np.ones((5,5))

In [ ]:
x * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [ ]:
np.random.random()

0.10381241700861932

In [ ]:
np.random.randint(1,100,5)

array([70, 27, 86, 75, 27])

In [ ]:
x = np.random.randint(1,100,(3,4))

In [ ]:
x

array([[51,  6,  2,  2],
       [90, 29, 70, 97],
       [ 2, 69, 45, 61]])

In [ ]:
np.mean(x)

43.666666666666664

In [ ]:
# row wise
np.mean(x, axis=1)

array([15.25, 71.5 , 44.25])

In [ ]:
# col wise
np.mean(x, axis=0)

array([47.66666667, 34.66666667, 39.        , 53.33333333])

In [ ]:
np.mean(x[2])

44.25

In [ ]:
np.mean(x[:, 0])

47.666666666666664

In [ ]:
np.var(x)

1127.0555555555554

In [ ]:
np.std(x)

33.571648091143146