In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, MinMaxScaler, StandardScaler

C:\Users\asus\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [17]:
df = pd.read_csv('SaratogaHouses.csv')

In [3]:
df.shape

(1728, 17)

In [4]:
df.head()

Unnamed: 0   price  lotSize  age  landValue  livingArea  pctCollege  \
0           1  132500     0.09   42      50000         906          35   
1           2  181115     0.92    0      22300        1953          51   
2           3  109000     0.19  133       7300        1944          51   
3           4  155000     0.41   13      18700        1944          51   
4           5   86060     0.11    0      15000         840          51   

   bedrooms  fireplaces  bathrooms  rooms          heating      fuel  \
0         2           1        1.0      5         electric  electric   
1         3           0        2.5      6  hot water/steam       gas   
2         4           1        1.0      8  hot water/steam       gas   
3         3           1        1.5      5          hot air       gas   
4         2           0        1.0      3          hot air       gas   

               sewer waterfront newConstruction centralAir  
0             septic         No              No         No  
1             septic         No              No         No  
2  public/commercial         No              No         No  
3             septic         No              No         No  
4  public/commercial         No             Yes        Yes

In [5]:
pd.unique(df['heating'])

array(['electric', 'hot water/steam', 'hot air'], dtype=object)

In [6]:
pd.unique(df['waterfront'])

array(['No', 'Yes'], dtype=object)

In [7]:
pd.unique(df['newConstruction'])

array(['No', 'Yes'], dtype=object)

In [8]:
pd.unique(df['sewer'])

array(['septic', 'public/commercial', 'none'], dtype=object)

In [9]:
pd.unique(df['fuel'])

array(['electric', 'gas', 'oil'], dtype=object)

In [18]:
label = LabelEncoder()
df['newConstruction'] = label.fit_transform(df['newConstruction'])
df['waterfront'] = label.fit_transform(df['waterfront'])

In [19]:
df.head()

Unnamed: 0   price  lotSize  age  landValue  livingArea  pctCollege  \
0           1  132500     0.09   42      50000         906          35   
1           2  181115     0.92    0      22300        1953          51   
2           3  109000     0.19  133       7300        1944          51   
3           4  155000     0.41   13      18700        1944          51   
4           5   86060     0.11    0      15000         840          51   

   bedrooms  fireplaces  bathrooms  rooms          heating      fuel  \
0         2           1        1.0      5         electric  electric   
1         3           0        2.5      6  hot water/steam       gas   
2         4           1        1.0      8  hot water/steam       gas   
3         3           1        1.5      5          hot air       gas   
4         2           0        1.0      3          hot air       gas   

               sewer  waterfront  newConstruction centralAir  
0             septic           0                0         No  
1             septic           0                0         No  
2  public/commercial           0                0         No  
3             septic           0                0         No  
4  public/commercial           0                1        Yes

In [20]:
onehot = OneHotEncoder()
sewer = onehot.fit_transform(df['sewer'].values.reshape(-1,1))

In [22]:
sewer

<1728x3 sparse matrix of type '<class 'numpy.float64'>'
	with 1728 stored elements in Compressed Sparse Row format>

In [23]:
sewer.toarray()

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
sewer = sewer.toarray()

In [27]:
df.drop(columns=['sewer'],inplace=True)

In [28]:
df.shape

(1728, 16)

In [29]:
df.head()

Unnamed: 0   price  lotSize  age  landValue  livingArea  pctCollege  \
0           1  132500     0.09   42      50000         906          35   
1           2  181115     0.92    0      22300        1953          51   
2           3  109000     0.19  133       7300        1944          51   
3           4  155000     0.41   13      18700        1944          51   
4           5   86060     0.11    0      15000         840          51   

   bedrooms  fireplaces  bathrooms  rooms          heating      fuel  \
0         2           1        1.0      5         electric  electric   
1         3           0        2.5      6  hot water/steam       gas   
2         4           1        1.0      8  hot water/steam       gas   
3         3           1        1.5      5          hot air       gas   
4         2           0        1.0      3          hot air       gas   

   waterfront  newConstruction centralAir  
0           0                0         No  
1           0                0         No  
2           0                0         No  
3           0                0         No  
4           0                1        Yes

In [30]:
X = df.values

In [31]:
X[0]

array([1, 132500, 0.09, 42, 50000, 906, 35, 2, 1, 1.0, 5, 'electric',
       'electric', 0, 0, 'No'], dtype=object)

In [32]:
X = np.c_[X,sewer]

In [33]:
X[0]

array([1, 132500, 0.09, 42, 50000, 906, 35, 2, 1, 1.0, 5, 'electric',
       'electric', 0, 0, 'No', 0.0, 0.0, 1.0], dtype=object)

In [35]:
# onehot.inverse_transform(sewer)

In [36]:
onehot = OneHotEncoder()
fuel = onehot.fit_transform(df['fuel'].values.reshape(-1,1)).toarray()

onehot = OneHotEncoder()
heating = onehot.fit_transform(df['heating'].values.reshape(-1,1)).toarray()

In [37]:
df.drop(columns=['fuel','heating'], inplace=True)

In [38]:
df['centralAir'] = label.fit_transform(df['centralAir'])

In [39]:
df.head()

Unnamed: 0   price  lotSize  age  landValue  livingArea  pctCollege  \
0           1  132500     0.09   42      50000         906          35   
1           2  181115     0.92    0      22300        1953          51   
2           3  109000     0.19  133       7300        1944          51   
3           4  155000     0.41   13      18700        1944          51   
4           5   86060     0.11    0      15000         840          51   

   bedrooms  fireplaces  bathrooms  rooms  waterfront  newConstruction  \
0         2           1        1.0      5           0                0   
1         3           0        2.5      6           0                0   
2         4           1        1.0      8           0                0   
3         3           1        1.5      5           0                0   
4         2           0        1.0      3           0                1   

   centralAir  
0           0  
1           0  
2           0  
3           0  
4           1

In [40]:
X = df.values

In [41]:
X = np.c_[X,sewer,fuel,heating]

In [42]:
X.shape

(1728, 23)

In [43]:
X[0]

array([1.000e+00, 1.325e+05, 9.000e-02, 4.200e+01, 5.000e+04, 9.060e+02,
       3.500e+01, 2.000e+00, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00])

In [44]:
st = StandardScaler()
X_st = st.fit_transform(X)

In [45]:
X_st[0]

array([-1.73104875, -0.80748259, -0.58729739,  0.4823004 ,  0.44108417,
       -1.36985441, -1.99095176, -1.41291539,  0.7161695 , -1.36770853,
       -0.88163155, -0.09357653, -0.22176638, -0.76221375, -0.0836242 ,
       -1.53471164,  1.56057287,  2.11795049, -1.50141177, -0.37796447,
        2.15999393, -1.35896559, -0.46019692])

In [46]:
minmax = MinMaxScaler()
X_minmax = minmax.fit_transform(X)

In [48]:
X_minmax[0]

array([0.        , 0.16558442, 0.00737705, 0.18666667, 0.12075655,
       0.06287944, 0.24193548, 0.16666667, 0.25      , 0.22222222,
       0.3       , 0.        , 0.        , 0.        , 0.        ,
       0.        , 1.        , 1.        , 0.        , 0.        ,
       1.        , 0.        , 0.        ])