In [1]:
import numpy as np

In [2]:
# ways to create array using numpy

In [3]:
# 1. using np.array()
np.array([4,5,67,8,23,23,5,67,7])

array([ 4,  5, 67,  8, 23, 23,  5, 67,  7])

In [4]:
# 2. using np.arange()
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(1,19,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [6]:
# 3. np.linspace() -> linear space
# by default it return 50 elements in a given range with equal gap
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [7]:
np.linspace(1,10,num=15)

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [8]:
np.linspace(1,10,num=15,retstep=True)

(array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
         4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
         7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ]),
 0.6428571428571429)

In [9]:
# 4. np.zeros()
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.identity(5,dtype=np.int32)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [14]:
np.identity(5) * 5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [17]:
# 5. np.random.random()
np.random.random()

0.0015186728137022154

In [18]:
np.random.random(5)

array([0.32306626, 0.43487949, 0.72067346, 0.98946201, 0.01710689])

In [20]:
np.random.random(size=(5,5))

array([[0.8105861 , 0.29743738, 0.99530811, 0.30081038, 0.67362703],
       [0.06667494, 0.65534513, 0.49611872, 0.40920903, 0.40420608],
       [0.6997607 , 0.71073349, 0.76146913, 0.08763628, 0.70248189],
       [0.8691807 , 0.98435746, 0.21005898, 0.43691968, 0.50678391],
       [0.49929544, 0.96857688, 0.12633156, 0.10066095, 0.81735506]])

In [23]:
np.random.randn(5)

array([ 1.64444869, -1.95002534, -0.82234809,  0.94059744, -1.29370439])

In [28]:
np.random.randn(4,4)

array([[-1.28445835,  0.37774482,  1.7617218 , -0.06098231],
       [ 2.56800099,  0.58751935, -0.21256297, -1.1253599 ],
       [-1.24348155, -0.99652521, -1.2429408 ,  0.64277235],
       [-0.6478465 ,  0.07227135, -2.54723027, -0.78618364]])

In [25]:
np.random.randint(1,10)

5

In [26]:
np.random.randint(1,10,5)

array([5, 2, 7, 8, 4])

In [27]:
np.random.randint(1,10,(5,5))

array([[3, 8, 7, 8, 5],
       [5, 8, 7, 5, 1],
       [4, 9, 2, 5, 2],
       [8, 4, 6, 9, 2],
       [3, 1, 4, 4, 6]])

### Numpy Array Slicing

In [29]:
x = np.random.randint(1,100,8)

In [30]:
x

array([38, 45, 35, 77, 95, 32, 92, 39])

In [31]:
x[0]

38

In [32]:
x[0:5]

array([38, 45, 35, 77, 95])

In [33]:
x[-1]

39

In [34]:
x = np.random.randint(1,100,(4,5))

In [35]:
x

array([[96, 49, 18, 41, 50],
       [23, 19,  8, 97, 34],
       [23, 73, 43, 46, 67],
       [24, 89, 54, 47, 36]])

In [36]:
x[0]

array([96, 49, 18, 41, 50])

In [37]:
x[1]

array([23, 19,  8, 97, 34])

In [38]:
x[0][0]

96

In [39]:
# x[row, col]
x[:,0]

array([96, 23, 23, 24])

In [40]:
x[:,0:1]

array([[96],
       [23],
       [23],
       [24]])

In [41]:
x[0:3,0:3]

array([[96, 49, 18],
       [23, 19,  8],
       [23, 73, 43]])

In [42]:
x[:,[1,3]]

array([[49, 41],
       [19, 97],
       [73, 46],
       [89, 47]])

In [44]:
x[:,[i for i in range(0,5,2)]]

array([[96, 18, 50],
       [23,  8, 34],
       [23, 43, 67],
       [24, 54, 36]])

# Numpy Methods

In [45]:
x = np.random.randint(1,100,20)

In [46]:
x

array([97, 34, 26, 75, 20, 13, 94, 85, 51, 52, 63, 37, 26, 13, 75, 91, 90,
       59, 75, 12])

In [47]:
x.shape

(20,)

In [48]:
x.reshape((4,5))

array([[97, 34, 26, 75, 20],
       [13, 94, 85, 51, 52],
       [63, 37, 26, 13, 75],
       [91, 90, 59, 75, 12]])

In [49]:
x.reshape((5,-1))

array([[97, 34, 26, 75],
       [20, 13, 94, 85],
       [51, 52, 63, 37],
       [26, 13, 75, 91],
       [90, 59, 75, 12]])

In [51]:
x.reshape((-1,2))

array([[97, 34],
       [26, 75],
       [20, 13],
       [94, 85],
       [51, 52],
       [63, 37],
       [26, 13],
       [75, 91],
       [90, 59],
       [75, 12]])

In [54]:
# convert 1D to 2D
# x.reshape((-1,1))

In [59]:
x

array([97, 34, 26, 75, 20, 13, 94, 85, 51, 52, 63, 37, 26, 13, 75, 91, 90,
       59, 75, 12])

In [55]:
np.max(x)

97

In [56]:
np.min(x)

12

In [57]:
np.argmax(x)

0

In [58]:
np.argmin(x)

19

In [65]:
np.argsort(x,kind='mergesort')

array([19,  5, 13,  4,  2, 12,  1, 11,  8,  9, 17, 10,  3, 14, 18,  7, 16,
       15,  6,  0], dtype=int64)

In [66]:
np.mean(x)

54.4

In [67]:
np.median(x)

55.5

In [68]:
x = np.reshape(x, (5,4))

In [69]:
x

array([[97, 34, 26, 75],
       [20, 13, 94, 85],
       [51, 52, 63, 37],
       [26, 13, 75, 91],
       [90, 59, 75, 12]])

In [70]:
np.mean(x)

54.4

In [71]:
# column wise
np.mean(x, axis=0)

array([56.8, 34.2, 66.6, 60. ])

In [72]:
# row wise
np.mean(x, axis=1)

array([58.  , 53.  , 50.75, 51.25, 59.  ])

In [73]:
x.shape

(5, 4)

In [74]:
# convert data from 2D to 1D
x.flatten()

array([97, 34, 26, 75, 20, 13, 94, 85, 51, 52, 63, 37, 26, 13, 75, 91, 90,
       59, 75, 12])

In [75]:
x.T

array([[97, 20, 51, 26, 90],
       [34, 13, 52, 13, 59],
       [26, 94, 63, 75, 75],
       [75, 85, 37, 91, 12]])