In [1]:
import numpy as np

In [2]:
np.array([1,2,4,5,6,3,5])

array([1, 2, 4, 5, 6, 3, 5])

In [4]:
print(np.array([1,3,5,6,6,"hi"]))

['1' '3' '5' '6' '6' 'hi']


In [5]:
print(np.array([1,3,5,6,6,10.55]))

[ 1.    3.    5.    6.    6.   10.55]


In [6]:
# range(start, stop, step)
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.random.randint(1,100)

43

In [11]:
np.random.randint(1,100,10)

array([78, 94, 67, 16, 75, 26, 78, 77, 74, 42])

In [12]:
# matrix
np.array([[4,5,7],[3,5,6],[6,3,7]])

array([[4, 5, 7],
       [3, 5, 6],
       [6, 3, 7]])

In [13]:
x = np.array([[4,5,7],[3,5,6],[6,3,7]])

In [15]:
x.shape

(3, 3)

In [16]:
x[0]

array([4, 5, 7])

In [17]:
x[0][0]

4

In [18]:
# dimension of data
x.ndim

2

In [19]:
x = np.random.randint(1,100,[6,4])

In [20]:
x

array([[51, 90, 75, 95],
       [84, 28, 32, 97],
       [28, 79, 78, 58],
       [59, 71, 54, 78],
       [13, 26, 48, 55],
       [27, 63, 77, 14]])

In [21]:
# transpose the data
x.T

array([[51, 84, 28, 59, 13, 27],
       [90, 28, 79, 71, 26, 63],
       [75, 32, 78, 54, 48, 77],
       [95, 97, 58, 78, 55, 14]])

In [22]:
x.shape

(6, 4)

In [23]:
# x.reshape(4,6)
x.reshape(2,12)

array([[51, 90, 75, 95, 84, 28, 32, 97, 28, 79, 78, 58],
       [59, 71, 54, 78, 13, 26, 48, 55, 27, 63, 77, 14]])

In [24]:
x.reshape(3,8)

array([[51, 90, 75, 95, 84, 28, 32, 97],
       [28, 79, 78, 58, 59, 71, 54, 78],
       [13, 26, 48, 55, 27, 63, 77, 14]])

In [25]:
# x.reshape(-1,3)
x.reshape(3,-1)

array([[51, 90, 75, 95, 84, 28, 32, 97],
       [28, 79, 78, 58, 59, 71, 54, 78],
       [13, 26, 48, 55, 27, 63, 77, 14]])

In [26]:
x.reshape(4,-1)

array([[51, 90, 75, 95, 84, 28],
       [32, 97, 28, 79, 78, 58],
       [59, 71, 54, 78, 13, 26],
       [48, 55, 27, 63, 77, 14]])

In [27]:
x

array([[51, 90, 75, 95],
       [84, 28, 32, 97],
       [28, 79, 78, 58],
       [59, 71, 54, 78],
       [13, 26, 48, 55],
       [27, 63, 77, 14]])

In [28]:
# convert data into 1D
y = x.flatten()

In [29]:
y

array([51, 90, 75, 95, 84, 28, 32, 97, 28, 79, 78, 58, 59, 71, 54, 78, 13,
       26, 48, 55, 27, 63, 77, 14])

In [30]:
np.max(y)

97

In [31]:
np.min(y)

13

In [32]:
np.mean(y)

57.5

In [33]:
np.median(y)

58.5

In [34]:
np.std(y)

25.220692562523602

In [35]:
np.var(y)

636.0833333333334

In [37]:
x

array([[51, 90, 75, 95],
       [84, 28, 32, 97],
       [28, 79, 78, 58],
       [59, 71, 54, 78],
       [13, 26, 48, 55],
       [27, 63, 77, 14]])

In [36]:
np.mean(x)

57.5

In [38]:
# mean of all rows
np.mean(x, axis=1)

array([77.75, 60.25, 60.75, 65.5 , 35.5 , 45.25])

In [39]:
# mean of all cols
np.mean(x, axis=0)

array([43.66666667, 59.5       , 60.66666667, 66.16666667])

In [40]:
y

array([51, 90, 75, 95, 84, 28, 32, 97, 28, 79, 78, 58, 59, 71, 54, 78, 13,
       26, 48, 55, 27, 63, 77, 14])

In [41]:
x

array([[51, 90, 75, 95],
       [84, 28, 32, 97],
       [28, 79, 78, 58],
       [59, 71, 54, 78],
       [13, 26, 48, 55],
       [27, 63, 77, 14]])

In [43]:
y[0:5]

array([51, 90, 75, 95, 84])

In [44]:
# it will return first 3 rows
x[0:3]

array([[51, 90, 75, 95],
       [84, 28, 32, 97],
       [28, 79, 78, 58]])

In [45]:
# it will return first 3 rows and first 2 cols
x[0:3, 0:2]

array([[51, 90],
       [84, 28],
       [28, 79]])

In [46]:
# it will return all the rows but only first 2 cols
x[:, 0:2]

array([[51, 90],
       [84, 28],
       [28, 79],
       [59, 71],
       [13, 26],
       [27, 63]])

In [47]:
# it will return all the rows but 0,2 and 3 col
x[:, [0,2,3]]

array([[51, 75, 95],
       [84, 32, 97],
       [28, 78, 58],
       [59, 54, 78],
       [13, 48, 55],
       [27, 77, 14]])