In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [2]:
df = pd.read_csv('headbrain.csv')

In [3]:
X = df['Head Size(cm^3)'].values
y = df['Brain Weight(grams)'].values

In [4]:
X = X.reshape(-1,1)
y = y.reshape(-1,1)

In [5]:
sc = StandardScaler()
X = sc.fit_transform(X)
y = sc.fit_transform(y)

In [6]:
X[:5]

array([[2.40886829],
       [0.28535333],
       [1.72023489],
       [0.39235214],
       [1.4897759 ]])

In [7]:
y[:5]

array([[ 2.0579083 ],
       [ 0.11763692],
       [ 0.43407603],
       [-0.00727325],
       [ 2.557549  ]])

In [29]:
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=110)

In [30]:
x_train.shape, x_test.shape

((189, 1), (48, 1))

In [31]:
regression = LinearRegression()
regression.fit(x_train, y_train)

LinearRegression()

In [32]:
regression.intercept_

array([0.02191652])

In [33]:
regression.coef_

array([[0.79491638]])

In [34]:
y_pred = regression.predict(x_test)

In [35]:
mean_squared_error(y_test, y_pred)

0.19519525946372362