In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, MinMaxScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report, confusion_matrix

C:\Users\asus\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
df = pd.read_csv('Churn_Modelling.csv')

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X_df = df.iloc[:,3:-1]
y = df.iloc[:,-1].values

In [5]:
pd.unique(X_df['Gender'])

array(['Female', 'Male'], dtype=object)

In [6]:
pd.unique(X_df['Geography'])

array(['France', 'Spain', 'Germany'], dtype=object)

In [7]:
lab = LabelEncoder()
X_df['Gender'] = lab.fit_transform(X_df['Gender'])

In [8]:
pd.unique(X_df['Gender'])

array([0, 1])

In [10]:
geog = X_df['Geography'].values
geog = np.reshape(geog, (-1,1))
onehot = OneHotEncoder()
geog = onehot.fit_transform(geog)

In [11]:
geog

<10000x3 sparse matrix of type '<class 'numpy.float64'>'
	with 10000 stored elements in Compressed Sparse Row format>

In [12]:
geog = geog.toarray()

In [13]:
geog

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [14]:
X_df.drop(columns=['Geography'], inplace=True)

In [15]:
X_df.shape

(10000, 9)

In [16]:
X_df.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  
0               1        101348.88  
1               1        112542.58  
2               0        113931.57  
3               0         93826.63  
4               1         79084.10

In [17]:
X = X_df.values
X = np.c_[X, geog]

In [18]:
minmax = MinMaxScaler()
X = minmax.fit_transform(X)

In [19]:
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.25)

In [20]:
x_train.shape

(7500, 12)

In [21]:
y_train.shape

(7500,)

In [22]:
logistic = LogisticRegression()
logistic.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [23]:
y_pred = logistic.predict(x_test)

In [24]:
accuracy_score(y_test, y_pred)

0.8136

In [27]:
y_test[:50]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1], dtype=int64)

In [28]:
y_pred[:50]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=int64)

In [29]:
confusion_matrix(y_test, y_pred)

array([[1921,   58],
       [ 408,  113]], dtype=int64)

In [30]:
x_test.shape

(2500, 12)

In [31]:
1921+113

2034

In [32]:
408+58

466

In [33]:
(1921 + 113) / (1921 + 58 + 408 + 113)

0.8136

In [34]:
precision_score(y_test, y_pred)

0.6608187134502924

In [35]:
recall_score(y_test, y_pred)

0.21689059500959693

In [37]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.97      0.89      1979
           1       0.66      0.22      0.33       521

    accuracy                           0.81      2500
   macro avg       0.74      0.59      0.61      2500
weighted avg       0.79      0.81      0.77      2500

